### ISSUE TITLE
Autoredirect doesn't get triggered

### ISSUE THREAD

**Issue by Gdewilde** [apideck-samples/file-picker#16]
When launching a test session on https://file-picker.apideck.dev/ and connecting with Dropbox, Vault doesn't automatically redirect back after making the connection. 

Example request: https://app.apideck.com/ecosystems/ckrg1f1vgrm5b0a9831hrxtk6/unify/logs/requests/798e052f-0003-4744-8276-7aefe15e6eab

**Comment by jakeprins** [comment]
Problem is related to the session refactor. 

Without being able to send a second query param to the redirectUrl (to add the jwt), it wasn't possible to fetch the connection state server-side so it's now being handled client-side (just like after a form submit). It's live so should be testable through file picker or importer
