### ISSUE TITLE
FilePicker: Use vaultjs instead of redirecting to hosted vault

### ISSUE THREAD

**Issue by thim81** [apideck-samples/file-picker#39]
The file-picker react component: When the user has no integration configured you are showing a message: `Go to vault to add file storage connectors with a link to your page`. 

How can we change that link, I couldn't find anything in the documentation.

**Comment by thim81** [comment]
Linked to https://apideck-io.slack.com/archives/C04FD1BLBLK/p1671620524998009

**Comment by jakeprins** [comment]
That link can't be changed. Also not sure why they would want that because the user needs to authorize connections (using vault). 

It would be an improvement if we start using React Vault (or Vault.js) instead of linking to Hosted Vault. Maybe we can create an issue for that.

**Comment by thim81** [comment]
Feedback from the customer:
Hey, yes, we are integrating your vault component within our application. So we would like to have the customers stay in our application. I think the message is also fine. But I would like to change the link to our url where the customer can configure their vault.

**Comment by thim81** [comment]
Feedback from Jake: 
Ah, I see. Currently, it’s not possible to change that link. We could add that, but we could also open that Vault component directly when clicking that link instead of redirecting to Hosted Vault. That might even be better.

**Comment by thim81** [comment]
@jakeprins that would mean introducing a new setting in FilePicker or Vault?

**Comment by jakeprins** [comment]
> @jakeprins that would mean introducing a new setting in FilePicker or Vault?

Replacing that link to hosted vault with the vault component does not require a new setting
